import Head from "next/head";
import Edit from "@/modules/manager/edit";

export default function Home() {
  return (
    <>
      <Head>
        <title>Checklists - Editando Checklist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Edit />
      </main>
    </>
  );
}
